script/seed.js, server/db/models/clothes.js, server/db/models/index.js
=> clothes models

server/db/models/transactions.js, server/db/models/transactions.spec.js
=> finished transacions model

server/db/models/index.js, test-specs/transactions-model.spec.js, test-specs/user-model.spec.js, test-specs/users-routes.spec.js
=> added spec folder

package.json, script/seed.js, server/db/models/user.js, test-specs/user-model.spec.js, test-specs/users-routes.spec.js
=> user model updated

package.json, server/api/index.js, server/api/transactions.js, server/db/models/transactions.js, test-specs/transactions-model.spec.js, test-specs/transactions-routes.spec.js
=> finished transaction routes

package-lock.json, package.json, script/seed.js, server/api/users.js, server/db/models/clothes.js, server/db/models/index.js, test-specs/clothes-model.spec.js
* [x ] added unit tests (or none needed)
---
=> User routes

server/db/models/user.js
=> User models

server/db/models/clothes.js
=> Fix: updated clothes test spec to reflcet FLOAT

script/seed.js, server/api/index.js, server/api/orders.js, server/db/models/index.js, server/db/models/orders.js, test-specs/order-routes.spec.js, test-specs/orders-model.spec.js
=> Update usemodel cart

server/admin.middleware.js, server/api/clothes.js, server/index.js
=> Restful routes

server/api/users.js, test-specs/users-routes.spec.js
=> Added Route users and admin

server/api/orders.js, server/api/users.js
=> fix: updated orders routes to reflect  isAdmin middleware

server/api/users.js
=> removed repeated route in user.js

test-specs/order-routes.spec.js
=> failing test pended

client/components/navbar.js
=> fix: fixed link to clothes in navbar

server/api/clothes.js, server/api/orders.js, server/api/users.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/orders.js
=> Implement guest feature

server/api/clothes.js, server/api/orders.js, server/api/users.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/orders.js
=> feature: created API routed for add/remove/view cart and for checkout

server/api/clothes.js, server/db/models/index.js, server/db/models/orders.js, server/db/models/transactions.js
=> Fix: fixed quantity functionality for add/remove routes

server/api/cart.js, server/db/models/orders.js, server/db/models/transactions.js
=> Fix: fixed cart routes

client/components/clothing-item.js
=> readded cart feature

client/components/all-clothes.js, client/components/cart.js, client/components/clothing-item.js, client/reducers/user.js
=> work: local storage for guest user

client/components/cart.js, client/components/cartItem.js, client/components/clothing-item.js, client/reducers/cart.js, client/reducers/item.js, public/style.css, server/api/cart.js, server/api/users.js
=> feature: view user cart

client/components/cart.js, client/store/user.spec.js, test-specs/orders-model.spec.js
=> Guest cart

client/components/cart.js
=> added comma

client/components/userProfile.js, client/reducers/user.js, server/api/users.js
=> Added profile update functionnality

client/components/cart.js, client/reducers/cart.js, public/style.css, server/api/cart.js
=> Fixed Cart Component

client/components/cart.js, client/components/cartItem.js, client/components/clothing-item.js, public/index.html
=> feature: guest can now add/remove

client/components/cart.js, client/components/cartItem.js, client/components/clothing-item.js, public/index.html
This reverts commit 8739147473f15d4d445a8335b90dfd529723a96c, reversing
changes made to 5a03d8f1074b099e92e527f92e24ee7763d76e4a.
---
=> Revert "Merge pull request #100 from The-Upper-Rest-Side/guest-cart"

client/components/all-clothes.js, client/components/cart.js, client/components/clothing-item.js, public/index.html, script/seed.js, server/admin.middleware.js
=> our final project 
